[package]
name = "kudrive-common"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
bytes = { workspace = true }
tokio = { workspace = true }
uuid = { workspace = true }
libp2p = { workspace = true }
